version: '3.8'

services:
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"

  api:
    build:
      dockerfile: Dockerfile
      context: "./server"
    environment:
      - PORT=5000
      - DB_NAME=postgres
      - DB_USER=postgres_ro
      - DB_PASS=0123456789
      - DB_HOST=voids-jobs.c2wwnfcaisej.eu-central-1.rds.amazonaws.com
      - DB_PORT=5432
      - WEATHER_API_KEY=3WWEVYKLNRDJ4DHHK7ASL5XFF
    volumes:
      - /app/node_modules
      - ./server:/app
   
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app